<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 * @see        NewsManager
 */
require_once('NewsManager.class.php');

class NewsManager_MySQLi extends NewsManager {

	/**
	 * 
	 * @var MySQLi
	 * @access protected
	 */
	protected  $db;


}
?>