<?php
/**
 * Classe représentant une news, créée à l'occasion d'un TP du tutoriel « La programmation orientée objet en PHP » disponible sur http://www.siteduzero.com/
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class News {

	/**
	 * 
	 * @var array
	 * @access protected
	 */
	protected  $erreurs = array();

	/**
	 * 
	 * @var int
	 * @access protected
	 */
	protected  $id;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $auteur;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $titre;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $contenu;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $dateAjout;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $dateModif;


	/**
	 * Constructeur de la classe qui assigne les données spécifiées en paramètre aux attributs correspondants.
	 * @access public
	 * @param array $valeurs 
	 * @return void
	 */

	public final  function __construct($valeurs = array()) {

	}


	/**
	 * @access public
	 * @param array $donnees 
	 * @return void
	 */

	public final  function hydrate($donnees) {

	}


	/**
	 * @access public
	 * @return bool const
	 */

	public final  function isNew() {

	}


	/**
	 * @access public
	 * @return bool const
	 */

	public final  function isValid() {

	}


	/**
	 * @access public
	 * @param int $id 
	 * @return void
	 */

	public final  function setId($id) {

	}


	/**
	 * @access public
	 * @param string $auteur 
	 * @return void
	 */

	public final  function setAuteur($auteur) {

	}


	/**
	 * @access public
	 * @param string $titre 
	 * @return void
	 */

	public final  function setTitre($titre) {

	}


	/**
	 * @access public
	 * @param string $contenu 
	 * @return void
	 */

	public final  function setContenu($contenu) {

	}


	/**
	 * @access public
	 * @param string $dateAjout 
	 * @return void
	 */

	public final  function setDateAjout($dateAjout) {

	}


	/**
	 * @access public
	 * @param string $dateModif 
	 * @return void
	 */

	public final  function setDateModif($dateModif) {

	}


	/**
	 * @access public
	 * @return array const
	 */

	public final  function erreurs() {

	}


	/**
	 * @access public
	 * @return array const
	 */

	public final  function id() {

	}


	/**
	 * @access public
	 * @return string const
	 */

	public final  function auteur() {

	}


	/**
	 * @access public
	 * @return string const
	 */

	public final  function titre() {

	}


	/**
	 * @access public
	 * @return string const
	 */

	public final  function contenu() {

	}


	/**
	 * @access public
	 * @return string const
	 */

	public final  function dateAjout() {

	}


	/**
	 * @access public
	 * @return string const
	 */

	public final  function dateModif() {

	}


}
?>