<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class NewsManager {


	/**
	 * @access protected
	 * @param News $news 
	 * @return void
	 */

	protected final  function add(News $news) {

	}


	/**
	 * @access protected
	 * @param News $news 
	 * @return void
	 */

	protected final  function update(News $news) {

	}


	/**
	 * @access public
	 * @param int $id 
	 * @return void
	 */

	public final  function delete($id) {

	}


	/**
	 * @access public
	 * @param News $news 
	 * @return void
	 */

	public final  function save(News $news) {

	}


	/**
	 * @access public
	 * @return int
	 */

	public final  function count() {

	}


	/**
	 * @access public
	 * @param int $debut 		
	 * @param int $limite 
	 * @return array
	 */

	public final  function getList($debut = -1, $limite = -1) {

	}


	/**
	 * @access public
	 * @param int $id 
	 * @return News
	 */

	public final  function getUnique($id) {

	}


}
?>