<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

abstract class NewsManager {


	/**
	 * Ajouter une news
	 * @access protected
	 * @param News $news 
	 * @return void
	 */

	protected abstract  function add(News $news) ;

	/**
	 * update une news
	 * @access protected
	 * @param News $news 
	 * @return void
	 */

	protected abstract  function update(News $news) ;

	/**
	 * delete une news
	 * @access public
	 * @param int $id 
	 * @return void
	 */

	public abstract  function delete($id) ;

	/**
	 * save une news
	 * @access public
	 * @param News $news 
	 * @return void
	 */

	public  function save(News $news) {

	}


	/**
	 * compter le nombre total de news
	 * @access public
	 * @return int
	 */

	public abstract  function count() ;

	/**
	 * obtenir la liste des newsdemandée
	 * @access public
	 * @param int $debut 
	 * @param int $limite 
	 * @return array
	 */

	public abstract  function getList($debut = -1, $limite = -1) ;

	/**
	 * Retourne une news precise
	 * @access public
	 * @param int $id 
	 * @return News
	 */

	public abstract  function getUnique($id) ;

}
?>