<?php
/**
 * Classe représentant une news, créée à l'occasion d'un TP du tutoriel « La programmation orientée objet en PHP » disponible sur http://www.siteduzero.com/
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class News {

	/**
	 * 
	 * @var array
	 * @access protected
	 */
	protected  $erreurs = array();

	/**
	 * 
	 * @var int
	 * @access protected
	 */
	protected  $id;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $auteur;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $titre;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $contenu;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $dateAjout;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $dateModif;
	const AUTEUR_INVALIDE = 1;
	const TITRE_INVALIDE = 2;
	const CONTENU_INVALIDE = 3;


	/**
	 * Constructeur de la classe qui assigne les données spécifiées en paramètre aux attributs correspondants.
	 * @access public
	 * @param array $valeurs 
	 * @return void
	 */

	public  function __construct($valeurs = array()) {

	}


	/**
	 * Méthode assignant les valeurs spécifiées aux attributs correspondant.
	 * @access public
	 * @param array $donnees 
	 * @return void
	 */

	public  function hydrate($donnees) {

	}


	/**
	 * Méthode permettant de savoir si la news est nouvelle.
	 * @access public
	 * @return bool const
	 */

	public  function isNew() {

	}


	/**
	 * Méthode permettant de savoir si la news est valide.
	 * @access public
	 * @return bool const
	 */

	public  function isValid() {

	}


	/**
	 * SETTERS
	 * @access public
	 * @param int $id 
	 * @return void
	 */

	public  function setId($id) {

	}


	/**
	 * @access public
	 * @param string $auteur 
	 * @return void
	 */

	public  function setAuteur($auteur) {

	}


	/**
	 * @access public
	 * @param string $titre 
	 * @return void
	 */

	public  function setTitre($titre) {

	}


	/**
	 * @access public
	 * @param string $contenu 
	 * @return void
	 */

	public  function setContenu($contenu) {

	}


	/**
	 * @access public
	 * @param string $dateAjout 
	 * @return void
	 */

	public  function setDateAjout($dateAjout) {

	}


	/**
	 * @access public
	 * @param string $dateModif 
	 * @return void
	 */

	public  function setDateModif($dateModif) {

	}


	/**
	 * GETTERS
	 * @access public
	 * @return array const
	 */

	public  function erreurs() {

	}


	/**
	 * @access public
	 * @return array const
	 */

	public  function id() {

	}


	/**
	 * @access public
	 * @return string const
	 */

	public  function auteur() {

	}


	/**
	 * @access public
	 * @return string const
	 */

	public  function titre() {

	}


	/**
	 * @access public
	 * @return string const
	 */

	public  function contenu() {

	}


	/**
	 * @access public
	 * @return string const
	 */

	public  function dateAjout() {

	}


	/**
	 * @access public
	 * @return string const
	 */

	public  function dateModif() {

	}


}
?>